# Generated by Django 4.2.15 on 2024-08-19 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('familly_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=50)),
                ('user_name', models.CharField(max_length=50, unique=True)),
                ('phone_number', models.CharField(max_length=22)),
                ('location', models.CharField(max_length=60)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
    ]
